include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  TEST_DISABLED: 'true'
  #BUILD_DISABLED: 'true'
  CODE_QUALITY_DISABLED: 'true'
  LICENSE_MANAGEMENT_DISABLED: 'true'
  BROWSER_PERFORMANCE_DISABLED: 'true'
  LOAD_PERFORMANCE_DISABLED: 'true'
  SAST_DISABLED: 'true'
  SECRET_DETECTION_DISABLED: 'true'
  DEPENDENCY_SCANNING_DISABLED: 'true'
  CONTAINER_SCANNING_DISABLED: 'true'
  DAST_DISABLED: 'true'
  REVIEW_DISABLED: 'true'
  CODE_INTELLIGENCE_DISABLED: 'true'
  PRODUCTION_DISABLED: 'true'

cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 
build:
  image: node:8.16.0-alpine
  stage: deploy
  before_script:
    - apk add --update --no-cache
    - apk --no-cache --virtual build-dependencies add python
    - npm install
    - npm install -g @quasar/cli
  script:
    - quasar build
    - firebase use dudu-solutions --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
